"""initial tables

Revision ID: 13cb3aac46e1
Revises: 
Create Date: 2025-07-27 23:34:16.096588

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13cb3aac46e1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('breeding',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('male_id', sa.Integer(), nullable=False),
    sa.Column('female_id', sa.Integer(), nullable=False),
    sa.Column('pair_date', sa.String(length=20), nullable=False),
    sa.Column('litter_count', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('calendar_event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('date', sa.String(length=20), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mouse',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('strain', sa.String(length=100), nullable=False),
    sa.Column('gender', sa.String(length=10), nullable=False),
    sa.Column('genotype', sa.String(length=50), nullable=False),
    sa.Column('dob', sa.String(length=20), nullable=False),
    sa.Column('cage', sa.String(length=20), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password', sa.String(length=128), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('cage_transfer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mouse_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.String(length=20), nullable=False),
    sa.Column('new_cage', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['mouse_id'], ['mouse.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('procedure',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mouse_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('date', sa.String(length=20), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['mouse_id'], ['mouse.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('weight',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mouse_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.String(length=20), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('food_given', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['mouse_id'], ['mouse.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('weight')
    op.drop_table('procedure')
    op.drop_table('cage_transfer')
    op.drop_table('user')
    op.drop_table('mouse')
    op.drop_table('calendar_event')
    op.drop_table('breeding')
    # ### end Alembic commands ###
