"""Added litter_date to breeding table

Revision ID: 422562f9d55b
Revises: 13cb3aac46e1
Create Date: 2025-07-31 18:55:30.601982

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '422562f9d55b'
down_revision = '13cb3aac46e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('breeding', schema=None) as batch_op:
        batch_op.add_column(sa.Column('litter_date', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('wean_date', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('breeding', schema=None) as batch_op:
        batch_op.drop_column('wean_date')
        batch_op.drop_column('litter_date')

    # ### end Alembic commands ###
