"""Add Pup model

Revision ID: a59c5fd2716c
Revises: daa6cde803bf
Create Date: 2025-07-31 22:06:13.141054

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a59c5fd2716c'
down_revision = 'daa6cde803bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pup',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('breeding_id', sa.Integer(), nullable=False),
    sa.Column('sex', sa.String(length=10), nullable=False),
    sa.Column('genotype', sa.String(length=50), nullable=True),
    sa.Column('birth_date', sa.String(length=20), nullable=False),
    sa.Column('wean_due', sa.String(length=20), nullable=True),
    sa.Column('weaned', sa.Boolean(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['breeding_id'], ['breeding.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pup')
    # ### end Alembic commands ###
