"""Added training and project fields to Mouse

Revision ID: daa6cde803bf
Revises: 422562f9d55b
Create Date: 2025-07-31 20:12:05.893872

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'daa6cde803bf'
down_revision = '422562f9d55b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mouse', schema=None) as batch_op:
        batch_op.add_column(sa.Column('training', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('project', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mouse', schema=None) as batch_op:
        batch_op.drop_column('project')
        batch_op.drop_column('training')

    # ### end Alembic commands ###
