"""Add Pup model

Revision ID: e5a1a18e45ad
Revises: a59c5fd2716c
Create Date: 2025-07-31 22:39:19.726011

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e5a1a18e45ad'
down_revision = 'a59c5fd2716c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pup', schema=None) as batch_op:
        batch_op.alter_column('sex',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=1),
               existing_nullable=False)
        batch_op.alter_column('birth_date',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Date(),
               existing_nullable=False)
        batch_op.drop_column('weaned')
        batch_op.drop_column('wean_due')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pup', schema=None) as batch_op:
        batch_op.add_column(sa.Column('wean_due', sa.VARCHAR(length=20), nullable=True))
        batch_op.add_column(sa.Column('weaned', sa.BOOLEAN(), nullable=True))
        batch_op.alter_column('birth_date',
               existing_type=sa.Date(),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
        batch_op.alter_column('sex',
               existing_type=sa.String(length=1),
               type_=sa.VARCHAR(length=10),
               existing_nullable=False)

    # ### end Alembic commands ###
